[package]
name = "net"
description = ""
authors = ["Greymouth <thejadenjack@gmail.com"]
readme = "README.md"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.9"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
