[package]
name = "short-game"
version = "0.1.0"
authors = ["aidan chelig <aidan.chelig@gmail.com>"]
edition = "2018"
resolver="2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.7.0", features = ["dynamic"] }
